### ISSUE TITLE
Reduce size of PublicKey

### ISSUE THREAD

**Issue by RobinZ16** [kryptnostic/krypto#30]
By reducing the size, we can enable 128bit functionality.

We can change $C_2$ to be size n by n instead of 2n by 2n (and 3n by 3n for the binary ops) and augment the matrices so that $t$ has size n.

**Comment by njhlai** [comment]
V2 will solve this (still require ulimit -s 32768, but it works for 128bit). The PR for V2 is [here](https://github.com/kryptnostic/krypto/pull/62). Close this when V2 is fully integrated.
